baseURL = "http://example.org/"
languageCode = "en-us"
title = "李玉平"
theme = "ivy"
disqusShortname = "YYmommy"
[menu]
[[menu.main]]
  identifier = 'blog'
  name = '日志'
  title = 'blog section'
  url = '/cn/daily/'
  weight = -110
[[menu.main]]
  identifier = 'about'
  name = "关于"
  title = 'blog section'
  url = '/cn/about/'
  weight = -11
[params]
footer = "&copy; [YuPing Li](/) 2022 - "
[params.logo.en]
img = "/images/logo.png"
url = "/"
alt = "YuPing Li"
tag = ""
